name: CavernGenerators
version: '${project.version}'
main: org.corbin.caverngenerators.CavernGenerators
api-version: '1.20'
depend: [Essentials]
commands:
  generators:
    description: Generator commands
    usage: /<command>
    aliases: [generator]
    permission: cavern.use
permissions:
  generators.give:
    description: Allows giving generators to players
    default: op
  generators.reload:
    description: Allows reloading of the generators
    default: op
